namespace WindivertDotnet
{
    public enum WINDIVERT_PARAM
    {
        WINDIVERT_PARAM_QUEUE_LENGTH = 0,
        WINDIVERT_PARAM_QUEUE_TIME = 1,
        WINDIVERT_PARAM_QUEUE_SIZE = 2,
        WINDIVERT_PARAM_VERSION_MAJOR = 3,
        WINDIVERT_PARAM_VERSION_MINOR = 4,
    }
}
